reverting change to xml mime-type from previous revision, since this broke a test - presumably the changed test needs to be ported to 1.4.x too:
Failed Tests Summary: 3 (3 new)
(new) org.exist.http.RESTServiceTest.testPut
(new) org.exist.http.RESTServiceTest.testPutWithCharset
(new) org.exist.http.RESTServiceTest.testXUpdate

Stacktraces :
(new) org.exist.http.RESTServiceTest.testPut
junit.framework.ComparisonFailure: Server returned content type application/xml expected:<[text]/xml> but was:<[application]/xml>
	at junit.framework.Assert.assertEquals(Assert.java:81)

git-svn-id: https://exist.svn.sourceforge.net/svnroot/exist/stable/eXist-1.4.x@13431 8784284e-840f-0410-bd5a-a6a6012a0d1a